package goryachev.common.util.html;


import goryachev.common.util.CMap;
import javafx.fxml.FXMLLoader;

/* loaded from: fqlite_next.jar:FxTextEditor.jar:goryachev/common/util/html/Html4SymbolEntities.class */
public class Html4SymbolEntities {
    private CMap<Object, Object> entities = new CMap<>();

    public Html4SymbolEntities() {
        add("nbsp", (char) 160);
        add("iexcl", (char) 161);
        add("cent", (char) 162);
        add("pound", (char) 163);
        add("curren", (char) 164);
        add("yen", (char) 165);
        add("brvbar", (char) 166);
        add("sect", (char) 167);
        add("uml", (char) 168);
        add(FXMLLoader.COPY_TAG, (char) 169);
        add("ordf", (char) 170);
        add("laquo", (char) 171);
        add("not", (char) 172);
        add("shy", (char) 173);
        add("reg", (char) 174);
        add("macr", (char) 175);
        add("deg", (char) 176);
        add("plusmn", (char) 177);
        add("sup2", (char) 178);
        add("sup3", (char) 179);
        add("acute", (char) 180);
        add("micro", (char) 181);
        add("para", (char) 182);
        add("middot", (char) 183);
        add("cedil", (char) 184);
        add("sup1", (char) 185);
        add("ordm", (char) 186);
        add("raquo", (char) 187);
        add("frac14", (char) 188);
        add("frac12", (char) 189);
        add("frac34", (char) 190);
        add("iquest", (char) 191);
        add("Agrave", (char) 192);
        add("Aacute", (char) 193);
        add("Acirc", (char) 194);
        add("Atilde", (char) 195);
        add("Auml", (char) 196);
        add("Aring ", (char) 197);
        add("AElig", (char) 198);
        add("Ccedil", (char) 199);
        add("Egrave", (char) 200);
        add("Eacute", (char) 201);
        add("Ecirc", (char) 202);
        add("Euml", (char) 203);
        add("Igrave", (char) 204);
        add("Iacute", (char) 205);
        add("Icirc", (char) 206);
        add("Iuml", (char) 207);
        add("ETH", (char) 208);
        add("Ntilde", (char) 209);
        add("Ograve", (char) 210);
        add("Oacute", (char) 211);
        add("Ocirc", (char) 212);
        add("Otilde", (char) 213);
        add("Ouml", (char) 214);
        add("times", (char) 215);
        add("Oslash", (char) 216);
        add("Ugrave", (char) 217);
        add("Uacute", (char) 218);
        add("Ucirc", (char) 219);
        add("Uuml", (char) 220);
        add("Yacute", (char) 221);
        add("THORN", (char) 222);
        add("szlig", (char) 223);
        add("agrave", (char) 224);
        add("aacute", (char) 225);
        add("acirc", (char) 226);
        add("atilde", (char) 227);
        add("auml", (char) 228);
        add("aring", (char) 229);
        add("aelig", (char) 230);
        add("ccedil", (char) 231);
        add("egrave", (char) 232);
        add("eacute", (char) 233);
        add("ecirc", (char) 234);
        add("euml", (char) 235);
        add("igrave", (char) 236);
        add("iacute", (char) 237);
        add("icirc", (char) 238);
        add("iuml", (char) 239);
        add("eth", (char) 240);
        add("ntilde", (char) 241);
        add("ograve", (char) 242);
        add("oacute", (char) 243);
        add("ocirc", (char) 244);
        add("otilde", (char) 245);
        add("ouml", (char) 246);
        add("divide", (char) 247);
        add("oslash", (char) 248);
        add("ugrave", (char) 249);
        add("uacute", (char) 250);
        add("ucirc", (char) 251);
        add("uuml", (char) 252);
        add("yacute", (char) 253);
        add("thorn", (char) 254);
        add("yuml", (char) 255);
        add("fnof", (char) 402);
        add("Alpha", (char) 913);
        add("Beta", (char) 914);
        add("Gamma", (char) 915);
        add("Delta", (char) 916);
        add("Epsilon", (char) 917);
        add("Zeta", (char) 918);
        add("Eta", (char) 919);
        add("Theta", (char) 920);
        add("Iota", (char) 921);
        add("Kappa", (char) 922);
        add("Lambda", (char) 923);
        add("Mu", (char) 924);
        add("Nu", (char) 925);
        add("Xi", (char) 926);
        add("Omicron", (char) 927);
        add("Pi", (char) 928);
        add("Rho", (char) 929);
        add("Sigma ", (char) 931);
        add("Tau", (char) 932);
        add("Upsilon", (char) 933);
        add("Phi", (char) 934);
        add("Chi", (char) 935);
        add("Psi", (char) 936);
        add("Omega", (char) 937);
        add("alpha", (char) 945);
        add("beta", (char) 946);
        add("gamma", (char) 947);
        add("delta", (char) 948);
        add("epsilon", (char) 949);
        add("zeta", (char) 950);
        add("eta", (char) 951);
        add("theta", (char) 952);
        add("iota", (char) 953);
        add("kappa", (char) 954);
        add("lambda", (char) 955);
        add("mu", (char) 956);
        add("nu", (char) 957);
        add("xi", (char) 958);
        add("omicron", (char) 959);
        add("pi", (char) 960);
        add("rho", (char) 961);
        add("sigmaf", (char) 962);
        add("sigma", (char) 963);
        add("tau", (char) 964);
        add("upsilon", (char) 965);
        add("phi", (char) 966);
        add("chi", (char) 967);
        add("psi", (char) 968);
        add("omega", (char) 969);
        add("thetasym", (char) 977);
        add("upsih", (char) 978);
        add("piv", (char) 982);
        add("bull", (char) 8226);
        add("hellip", (char) 8230);
        add("prime", (char) 8242);
        add("Prime", (char) 8243);
        add("oline", (char) 8254);
        add("frasl", (char) 8260);
        add("weierp", (char) 8472);
        add("image", (char) 8465);
        add("real", (char) 8476);
        add("trade", (char) 8482);
        add("alefsym", (char) 8501);
        add("larr", (char) 8592);
        add("uarr", (char) 8593);
        add("rarr", (char) 8594);
        add("darr", (char) 8595);
        add("harr", (char) 8596);
        add("crarr", (char) 8629);
        add("lArr", (char) 8656);
        add("uArr", (char) 8657);
        add("rArr", (char) 8658);
        add("dArr", (char) 8659);
        add("hArr", (char) 8660);
        add("forall", (char) 8704);
        add("part", (char) 8706);
        add("exist", (char) 8707);
        add("empty", (char) 8709);
        add("nabla", (char) 8711);
        add("isin", (char) 8712);
        add("notin", (char) 8713);
        add("ni", (char) 8715);
        add("prod", (char) 8719);
        add("sum", (char) 8721);
        add("minus", (char) 8722);
        add("lowast", (char) 8727);
        add("radic", (char) 8730);
        add("prop", (char) 8733);
        add("infin", (char) 8734);
        add("ang", (char) 8736);
        add("and", (char) 8743);
        add("or", (char) 8744);
        add("cap", (char) 8745);
        add("cup", (char) 8746);
        add("int", (char) 8747);
        add("there4", (char) 8756);
        add("sim", (char) 8764);
        add("cong", (char) 8773);
        add("asymp", (char) 8776);
        add("ne", (char) 8800);
        add("equiv", (char) 8801);
        add("le", (char) 8804);
        add("ge", (char) 8805);
        add(HTML4.SUB, (char) 8834);
        add(HTML4.SUP, (char) 8835);
        add("nsub", (char) 8836);
        add("sube", (char) 8838);
        add("supe", (char) 8839);
        add("oplus", (char) 8853);
        add("otimes", (char) 8855);
        add("perp", (char) 8869);
        add("sdot", (char) 8901);
        add("lceil", (char) 8968);
        add("rceil", (char) 8969);
        add("lfloor", (char) 8970);
        add("rfloor", (char) 8971);
        add("lang", (char) 9001);
        add("rang", (char) 9002);
        add("loz", (char) 9674);
        add("spades", (char) 9824);
        add("clubs", (char) 9827);
        add("hearts", (char) 9829);
        add("diams", (char) 9830);
        add("quot", '\"');
        add("amp", '&');
        add("lt", '<');
        add("gt", '>');
        add("OElig", (char) 338);
        add("oelig", (char) 339);
        add("Scaron", (char) 352);
        add("scaron", (char) 353);
        add("Yuml", (char) 376);
        add("circ", (char) 710);
        add("tilde", (char) 732);
        add("ensp", (char) 8194);
        add("emsp", (char) 8195);
        add("thinsp", (char) 8201);
        add("zwnj", (char) 8204);
        add("zwj", (char) 8205);
        add("lrm", (char) 8206);
        add("rlm", (char) 8207);
        add("ndash", (char) 8211);
        add("mdash", (char) 8212);
        add("lsquo", (char) 8216);
        add("rsquo", (char) 8217);
        add("sbquo", (char) 8218);
        add("ldquo", (char) 8220);
        add("rdquo", (char) 8221);
        add("bdquo", (char) 8222);
        add("dagger", (char) 8224);
        add("Dagger", (char) 8225);
        add("permil", (char) 8240);
        add("lsaquo", (char) 8249);
        add("rsaquo", (char) 8250);
        add("euro", (char) 8364);
    }

    protected void add(String element, char c) {
        this.entities.put(element, Character.valueOf(c));
        this.entities.put(Character.valueOf(c), element);
    }

    public synchronized String lookupElement(char c) {
        return (String) this.entities.get(Character.valueOf(c));
    }

    public synchronized Character lookupChar(String element) {
        return (Character) this.entities.get(element);
    }
}
